apiVersion: v1
kind: Service
metadata:
  name: coredns
  namespace: kube-system
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9153"
  labels:
    k8s-app: coredns
    kubernetes.io/name: "CoreDNS"
spec:
  ipFamilyPolicy: PreferDualStack
  selector:
    k8s-app: coredns
  clusterIP: ${cluster_dns_service_ip}
  clusterIPs:
  - ${cluster_dns_service_ip}
  - ${cluster_dns_service_ip_v6}
  ports:
    - name: dns
      port: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      protocol: TCP
